<SoundButton@MDRectangleFlatButton>:
	line_color: "black"

MDBoxLayout:
	orientation: "vertical"
	MDBoxLayout:
		md_bg_color: app.theme_cls.primary_color
		size_hint_y: None
		height: 35
	MDGridLayout:
		id: pad
		cols: 4
		rows: 4
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton:
		SoundButton: